### ISSUE TITLE
Uncaught ReferenceError: global is not defined using 2.x version in the Browser

### ISSUE THREAD

**Issue by lholmquist** [nodeshift/opossum#338]
## Steps to Produce Error:

using the jQuery example from https://github.com/nodeshift-starters/opossum-examples/tree/master/jquery

I've updated to use Opossum@latest and receive this error in the developer console
```
opossum.js:10 Uncaught ReferenceError: global is not defined
    at opossum.js:10
(anonymous) @ opossum.js:10
```

Previously, in the 1.x version, this "global" variable use to be called "window". 

There are 2 webpack configs now.  one looks to be node only and the other is a web based one. 

@helio-frota @lance why are there 2 configs now?  It looks like the "opossum.js" that is distributed with the library is a node specific version,  and the "browser-test.js" file that gets distributed actually works in the browser.  shouldn't we just have on config and one file?

**Comment by helio-frota** [comment]
@lholmquist that was our first solution when moving forward with the prometheus integration.

More details about that starting [here](https://github.com/nodeshift/opossum/pull/283#issuecomment-472595042)

**Comment by lance** [comment]
@lholmquist so I think the webpack configuration that we run for the browser tests should also be generating an opossum.js for browser usage. I didn't look closely enough at what was happening here with the PR that @helio-frota linked above, and since all of the browser tests passed, did not realize that we were no longer generating an opossum.js file for use in the browser. My fault - I don't think there is any need to produce a node specific opossum.js in the dist dir, since node users will just use the package and index.js is the proper entry point for that.
