### ISSUE TITLE
module/globals/singletons

### ISSUE THREAD

**Issue by mcollina** [nodeshift/opossum#357]
I've been reviewing the code for Opossum, and I have been wondering if you would take a PR/help to remove the use of module singletons in the library.

Maintaining a list of all the created circuits for example prevents them to be garbage collected, creating a memory leak if `.shutdown()` is not called properly. Moreover, the use of a global Hystrix stream prints out the "MaxListeners" warning as well. Considering that multiple version of a module might coexists in the same Node application, I would recommend to avoid using singletons completely, as an example:

1. remove tracking of all the created circuits, leaving this feature to the user
2. make the HystrixStream optional when creating a circuit, `circuitBreaker(func, { hystrixStream: new HystrixStream())`, leaving making it app-wise to the end user

I know these are semver-major changes and big refactorings, and if you dedice to go this route I'm happy to help!

**Comment by lance** [comment]
@mcollina I'm happy you have eyes on it; of course we would welcome your collaboration. 

I have mixed feelings about keeping track of the circuits as they are created. When Prometheus metrics were introduced, we held [a reference to the last circuit created](https://github.com/nodeshift/opossum/commit/ff29f2e3ce77477aa3656167734bf1584239e89a), due to the way these metrics were implemented. Shortly after that release, there was a [feature request](https://github.com/nodeshift/opossum/issues/340) to maintain a full list. But both of these implementations felt like hacks at the time, and both were made in service of the metrics modules. 

Leaving that feature to the user is probably fine. That said, I think `shutdown()` is still important. :)

I currently have a [PR](https://github.com/nodeshift/opossum/pull/350) open which removes both Prometheus and Hystrix metrics from the circuit breaker module (not completely yet, but that is the goal). I think this capability can come from user land as well, since neither need any non-public information provided by the circuit. It's all done with events.

Unrelated, but also semver-major is the `factory()` function in index.js. I have been considering removing this altogether and instead just exposing the `CircuitBreaker` constructor.

Can I ask what project you are using `opossum` for (if at all)?

**Comment by mcollina** [comment]
One of my clients at NearForm is building a microservice system that heavily rely on Opossum, and they have been experiencing some memory leaks because they where not calling `shutdown`.

I think just going with a `CircuitBreaker` constructor would be good, I like the factory as it leaves more flexibility on the table, but the class approach is also very workable, and more intuitive in this case.

**Comment by lance** [comment]
@mcollina I will push a new release with all of the changes this week

**Comment by mcollina** [comment]
Amazing work! Thanks!

**Comment by lance** [comment]
4.0.0 has been released

**Comment by mcollina** [comment]
Amazing!
