### ISSUE TITLE
Missing/incorrect info in the doc

### ISSUE THREAD

**Issue by MathieuAA** [nodeshift/opossum#453]
Hello there!

Just noticed that `rollingCountDuration` isn't present in the official documentation [there](https://nodeshift.dev/opossum/#circuitbreaker).
As for `allowWarmUp`, here's the description:
> determines whether to allow failures without opening the circuit during a brief warmup period (this is the rollingCountDuration property). Default: false allow before enabling the circuit. This can help in situations where no matter what your errorThresholdPercentage is, if the first execution times out or fails, the circuit immediately opens. Default: 0 

As it has a boolean value, I find it weird that the default is `0` and that there's another default `false` in the same text.

**Comment by MathieuAA** [comment]
Shouldn't it be:
```
* @param {boolean} options.allowWarmUp determines whether to allow failures
 * without opening the circuit during a brief warmup period (this is the
 * `rollingCountDuration` property). Default: false, allow before enabling the circuit. 
* @param {Number} options.rollingCountDuration This can help in situations where no
 * matter what your `errorThresholdPercentage` is, if the first execution
 * times out or fails, the circuit immediately opens. Default: 0
```
? If so, I can submit a PR for that.

**Comment by helio-frota** [comment]
> Just noticed that rollingCountDuration isn't present in the official documentation there.

@MathieuAA hi, thanks for catch this. I did a search in the git history and I start to think that rollingCountDuration is a typo because this property was never added to the source code.

Also looking the PR which adds the allowWarmUp property, the commit message points to rollingCountTimeout.
https://github.com/nodeshift/opossum/pull/218/commits/2fea233d3a9701ffeabc5bf353cd13df39837888

"The warmup duration is the value provided for options.rollingCountTimeout."

So probably the docs should be rollingCountTimeout instead of rollingCountDuration. 

> As it has a boolean value, I find it weird that the default is 0 and that there's another default false in the same text.

Yeah , I think that makes sense to remove only the ` Default: 0` at the end and change from `rollingCountDuration` to `rollingCountTimeout`
