### ISSUE TITLE
Fallback function is being executed when errorFilter is applied

### ISSUE THREAD

**Issue by jerrin** [nodeshift/opossum#540]
## Steps to Produce Error:

According to https://github.com/nodeshift/opossum#fallback, the fallback function is supposed to be executed only when the circuit is open. But, when the error filter returns `true`, (for eg: error filter is applied to exclude HTTP 404, `errorFilter: err => err.statusCode < 500`)  the circuit remain closed and the fallback function is still being executed.

The issue seems to be here:
https://github.com/nodeshift/opossum/blob/3cb7de98259ecbbfed4dcf9b8ee5187367049907/lib/circuit.js#L658-L664

Would you be able to check if the fallback is supposed to be called in this scenario? 
Thanks

**Comment by lance** [comment]
Hi @jerrin. This is a good catch. It's actually working as intended, but the docs don't reflect that. A little over a year ago, this was discussed in a pull request. My [original ask](https://github.com/nodeshift/opossum/pull/389/files#r352904812) was to change this behavior so that fallback would not be called. But ultimately [we didn't go that route](https://github.com/nodeshift/opossum/pull/389#issuecomment-562309208) because it was considered a breaking change. @lholmquist should we revisit this?

**Comment by lholmquist** [comment]
This must have slipped through the email cracks,  will review today

**Comment by lholmquist** [comment]
It does feel a little odd that if the error filter "succceds" that we are still calling the fallback,  that scenario should be considered a success.   

I have no problems with doing a semver-major change to update this.

**Comment by jerrin** [comment]
Thank you both for looking into this 👍

**Comment by lholmquist** [comment]
Just released this fix in 6.0.0
