### ISSUE TITLE
Will not install on Node 11.5.0

### ISSUE THREAD

**Issue by ruslanrusu** [nodeshift/opossum#541]
Awesome library made the prototype and works perfectly. When i want to integrated in my mains service
faced the engine version issue. Was wondering why will that happen and if there is any way around it. 

## Steps to Produce Error:

node -v
v11.15.0

yarn add opossum
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error opossum@5.1.3: The engine "node" is incompatible with this module. Expected version "^15 || ^14 || ^12 || ^10". Got "11.15.0"

**Comment by lholmquist** [comment]
Hi,  we only support the Current version of Node, which is 15 atm, and LTS versions(the even number releases).    Which corresponds to how Node supports versions,  https://nodejs.org/en/about/releases/

My recommendation is to upgrade the node version if possible since version of 11 is a bunch of revisions behind.   While not really recommended,  you could just install opossum@5.0.1 since that is before we updated the engines
