### ISSUE TITLE
Configuration similar to permittedNumberOfCallsInHalfOpenState in resilience4j

### ISSUE THREAD

**Issue by vmal3951** [nodeshift/opossum#613]
As per my understanding, opossum makes the circuit to `CLOSE` state from the `HALF_OPEN` on the first success fire. But in the resilience4j implementation for java (https://resilience4j.readme.io/) has some options to configure the number of tries in the `HALF_OPEN` state. That option is `permittedNumberOfCallsInHalfOpenState`. So it will try that amount of calls first and evaluate the error percentage before closing the circuit again.

Is there any similar configuration here in the Opossum that I have missed?
or can anyone please give me an example to implement such a requirement?

**Comment by lholmquist** [comment]
The only thing that is close is the `options.resetTimeout`, which is the time in milliseconds to wait before
 setting the breaker to `halfOpen` state, and trying the action again.

but i don't think that takes care of that use case.

**Comment by lance** [comment]
> So it will try that amount of calls first and evaluate the error percentage before closing the circuit again.

Interesting. Currently, one would say that `opossum` only closes the circuit in the event of 0% error rate, with one try. But in your scenario, you would like to, for example keep a running tally of the error rate for a `HALF_OPEN` circuit, for a set number of calls, `N`. And if/when the error rate goes below that threshold, the circuit is `CLOSED`, otherwise, after the circuit has been fired `N` times in the `HALF_OPEN` state, it is `OPENED` again. Is this a correct understanding?

I can see a potential benefit for this if you are, for example, calling a really flaky service that you expect to fail often. But for that use case, could you not set the `errorThresholdPercentage` and the `resetTimeout` to be quite low? It's not exactly the same, but I'm curious how the behavior would compare in terms of total time spent in `HALF_OPEN` `CLOSED` and `OPEN` states.

**Comment by lance** [comment]
@lholmquist I am going to close this as there seem to be no plans to address it. Feel free to reopen if you think otherwise.
