### ISSUE TITLE
Generic type parameter from function is omitted

### ISSUE THREAD

**Issue by kevcodez** [nodeshift/opossum#670]
When using a generic type parameter in the inner function, it seems to be omitted.

```ts
const getFieldCB = new CircuitBreaker(getField);

async function getField<T>({ hash, key }: { hash: string; key: string }): Promise<null | T> {
  const entry = await redisInstance().hgetBuffer(hash, key);

  return decompress<T>(entry);
}
```

```ts
getFieldCB.fire({hash: 'a', key: 'b'})
```

Expected return value: `Promise<null | T>` (as defined on the function)
Actual return value: `Promise<unknown>`

**Comment by lance** [comment]
@kevcodez can you help me understand how that would work? Here is the type definition for the constructor.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4feea54144f81eba59ebdf17bb9ab48dae88db15/types/opossum/index.d.ts#L14-L17

We cannot know in advance what the return type of the supplied function will be (if anything). That's why it's defined as `unknown` in the type definition. I don't know how to statically declare the supplied function type in a way that would provide the feature you are asking for.

**Comment by lance** [comment]
@lholmquist do you have TS gurus on your team that could take a look at this?

**Comment by lholmquist** [comment]
I might be able to ask a few folks

**Comment by lance** [comment]
> I might be able to ask a few folks

@lholmquist any luck?

**Comment by lholmquist** [comment]
closing
