### ISSUE TITLE
Opossum is causing DepracationWarning from Buffer()

### ISSUE THREAD

**Issue by RoyBkker** [nodeshift/opossum#681]
## Node.js Version:
14.x

## Operating System:
AWS Lambda

Error:
`ERROR (node:18) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. at showFlaggedDeprecation (buffer.js:198:11) at new Buffer (buffer.js:282:3) at null.dispatchHttpRequest (/var/task/node_modules/axios/lib/adapters/http.js:36:16) at new Promise (<anonymous>) at Object.httpAdapter (/var/task/node_modules/axios/lib/adapters/http.js:18:10) at Function.axiosAdapter (/var/task/src/http/rest/lib/apiInstance.ts:21:68) at null.<anonymous> (/var/task/node_modules/opossum/lib/circuit.js:605:38) at new Promise (<anonymous>) at CircuitBreaker2.call (/var/task/node_modules/opossum/lib/circuit.js:581:12) at CircuitBreaker2.fire (/var/task/node_modules/opossum/lib/circuit.js:499:22)`

**Comment by lance** [comment]
Hi @RoyBkker - `opossum` actually does not use the `Buffer` class at all. You can see by grepping for `Buffer` in .js files and the library.

```console
opossum on  main [$] is 📦 v6.4.0 via  v16.15.1 on ☁️  lanceball@gmail.com
❯ rg Buffer lib *.js
```

From your stack trace, it appears that the problem is in Axios and was fixed a while back in this PR https://github.com/axios/axios/issues/1555. Are you sure you are using the latest version of that module?
