### ISSUE TITLE
maxSockets vs Opossum capacity

### ISSUE THREAD

**Issue by Samjin** [nodeshift/opossum#702]
Node docs says if request exceeds maxSockets, it'll put those requests in the queue, but based on what Opossum documented, the `capacity` will reject all requests that suppose to be queued. 

For a high traffic app with default `maxSockets:infinity`, it'll keep creating new connections until Opossum capacity is met unless there is enough free socket to reuse. In case of limit free sockets, new requests should be queued rather than killed by current Opossum capacity. Otherwise, app will always trigger the Opossum capacity limit. 

My question is - **does Opossum capacity include queued request**? The doc seems to suggest that it's not tracking queued requests. 

>If the number currently executing function calls is equal to options.capacity, further calls to fire() are rejected until at least one of the current requests completes

Can someone explain me how does `capacity` work with `maxSockets` setting?

**Comment by lance** [comment]
Hi @Samjin the `capacity` configuration option is used to determine how many concurrent invocations of the function may exist at any one moment. This attribute, however, is not correlated with Node.js' `maxSockets` option, since a function invocation may or may not involve a socket. The default value for `capacity` is `Number.MAX_SAFE_INTEGER` so it's fairly large and certainly larger than the total number of sockets that could be open at one time for a single process. The only tracking that opossum does related to `capacity` is to monitor the number of concurrently execution function calls for a circuit. When the `capacity` limit is reached, subsequent calls to `fire()` are rejected. Does this help clarify?

**Comment by Samjin** [comment]
That make sense in terms of they are not 1 to 1 mapping to each other. 
Do you have any suggestion for how to set `capacity` and `maxSockets`? I'm leaning towards setting high capacity value than maxSockets as we don't want to trigger circuit breaker before maxSockets are even reached..

**Comment by lance** [comment]
I would simply leave `capacity` as the default (`Number.MAX_SAFE_INTEGER`) unless you have a reason to restrict the number of concurrent invocations. I suspect the number of open sockets available to your process will be less than this maximum.

**Comment by lance** [comment]
Closing for now as resolved. If you need further assistance, @Samjin please reopen this or create a new issue.
