### ISSUE TITLE
Abort controller is controlling at the breaker level, not for each run

### ISSUE THREAD

**Issue by fuliisrobin** [nodeshift/opossum#780]
## Node.js Version:
19.6.0
## Operating System:
Linux PowerHorse 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
## Steps to Produce Error:
Hi, this is really a good library to implement nodejs layer circuit breaker! It supports most of our circuit breaker requirements, however, when we're dealing with timeouts,  the current design of circuit breaker can only control the abortController at the breaker level, which means, when there is one timeout happens, all the running tasks fired by this breaker will be aborted.

Is this intentionally designed like this or am I missing anything? I'm able to overcome this by using AsyncLocalStorage, however, that solution looks like a bit tricky.

**Comment by lance** [comment]
Hi @fuliisrobin. Thanks for your kind words about the module! Yes, the intent is that when a circuit times out, an assumption is made that all other ongoing requests to the same endpoint will time out as well. Otherwise, I believe that an abortController would need to be provided for each call to `circuit.fire()`. I understand this may not be ideal for your scenario, and I'm curious what you are doing with AsyncLocalStorage to address the situation.

**Comment by lholmquist** [comment]
Closing due to no response
